### ISSUE TITLE
feat: JavaScript stacktrace

### ISSUE THREAD

**Issue by MNorgren** [capacitor-community/firebase-crashlytics#39]
**Is your feature request related to a problem? Please describe:**
When I view my crashlytic events, the stack trace does not reveal the actual stack trace of where it occurred in my angular application.

**Describe the solution you'd like:**
I'd like to be able to see the stack trace of where the crash or non-fatal exception occurred in my angular code, or at least some information to help me track it down.

**Describe alternatives you've considered:**
Not sure if there are other alternatives?

**Additional context:**
Here is an image of the stack trace on the main dashboard:
![image](https://user-images.githubusercontent.com/3640233/121738223-8db5d380-cabf-11eb-936a-c9b391dfb48a.png)

And the detailed stack trace:
![image](https://user-images.githubusercontent.com/3640233/121738277-a0c8a380-cabf-11eb-9988-42ef4862d164.png)

**Comment by robingenz** [comment]
Thank you for this interesting request.
I had already thought about this myself.
As far as I know this is unfortunately not possible. (If someone knows more and I am wrong, please point me to it.)
The native stacktrace has no references to the JS code of the WebView.
Even if there were references, the JS code in the production build would still be obfuscated and you would need the source maps.

One way to get more information would be to use [`setContext`](https://github.com/capacitor-community/firebase-crashlytics#setcontext) and [`addLogMessage`](https://github.com/capacitor-community/firebase-crashlytics#addlogmessage).

Another way to log non-fatal errors would be to use tools such as [Sentry](https://sentry.io/for/angular/), which supports error monitoring on the web.

However, in terms of crashes, the stack trace from Firebase Crashlytics should be sufficient in most cases. App crashes are usually caused by errors in the native code and can only be fixed there, regardless of where in the JS code the plugin (o.s.) was called.

I am closing this issue, because in my opinion this feature request cannot be implemented.

I would be happy if there are possibilities after all and I could open this issue again.

**Comment by NLueg** [comment]
Hi there!
It actually is possible to utilize the JavaScript stacktrace. I previously used `cordova-plugin-firebasex` which implements this.
I just inspired myself on their implementation and created the PR #50 to also add the functionality to this plugin!

**Comment by robingenz** [comment]
Hi @NLueg, 
thank you very much for this tip. That sounds very exciting! I will have a look at your PR in the next few days (i'm very busy at the moment, sorry). In that case, I'll reopen this issue.

**Comment by robingenz** [comment]
Resolved by #50

**Comment by sSarahlei** [comment]
Will using stacktrace-js to generate the stack trace hurt performance on production (As it's based on source maps)?

**Comment by NLueg** [comment]
@sSarahlei no but the stack trace you receive won't be that helpful (see https://github.com/capacitor-community/firebase-crashlytics/pull/50#issuecomment-955171783).
You will (more or less) still see where the exception came up. But just because you use stacktrace-js the source maps are not integrated.

**Comment by sSarahlei** [comment]
Thank you very much for the quick response!
